<a href="https://colab.research.google.com/github/Sefinsha-b/Angular-Crud/blob/main/Numpy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

System Specification

In [ ]:
! cat /proc/cpuinfo

processor	: 0
vendor_id	: AuthenticAMD
cpu family	: 23
model		: 49
model name	: AMD EPYC 7B12
stepping	: 0
microcode	: 0xffffffff
cpu MHz		: 2250.000
cache size	: 512 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid tsc_known_freq pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw topoext ssbd ibrs ibpb stibp vmmcall fsgsbase tsc_adjust bmi1 avx2 smep bmi2 rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 clzero xsaveerptr arat npt nrip_save umip rdpid
bugs		: sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass retbleed
bogomips	: 4500.00
TLB s

In [ ]:
! cat /proc/meminfo

MemTotal:       13297228 kB
MemFree:         9905124 kB
MemAvailable:   12499024 kB
Buffers:           62468 kB
Cached:          2675540 kB
SwapCached:            0 kB
Active:           692788 kB
Inactive:        2518116 kB
Active(anon):        884 kB
Inactive(anon):   421084 kB
Active(file):     691904 kB
Inactive(file):  2097032 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:               336 kB
Writeback:             0 kB
AnonPages:        472932 kB
Mapped:           228244 kB
Shmem:              1156 kB
KReclaimable:      92832 kB
Slab:             119988 kB
SReclaimable:      92832 kB
SUnreclaim:        27156 kB
KernelStack:        3968 kB
PageTables:         9828 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     6648612 kB
Committed_AS:    2522736 kB
VmallocTotal:   34359738367 kB
VmallocUsed:        8728 kB
VmallocChunk:          0 kB
Percpu:          

In [ ]:
! pip install pandas

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import pandas as pd


#print function


In [ ]:
print("Machine LEARNING")

Machine LEARNING


In [ ]:
print("machine learning"+ "project")

machine learningproject


In [ ]:
print(8+3)


11


# Data types

 Immutable objects:

 1.init
 2.float
 3.string
 4.bool
 5.tuple


 Mutable objects:

 1.List
 2.Set
 3.Dictionary

#List

In [ ]:
my_list=[1,2,3,4]
print(my_list)
type(my_list)

[1, 2, 3, 4]


list

In [ ]:
#list can have multiple datatypes
my_list=[1,1,2,3,"english","true"]
print(my_list)

[1, 1, 2, 3, 'english', 'true']


In [ ]:
#addd elements in a list
my_list=[1,1,2.8,3,"english","true"]
my_list.append(8)
print(my_list)

[1, 1, 2.8, 3, 'english', 'true', 8]


In [ ]:

#print elements by using index
my_list=[1,1,2.8,3,"english","true"]
print(my_list[4])

english


In [ ]:
#list allows duplicate values
my_list =[1,1,2.8,3,"english","true",1111,1]
print(my_list)
print(len(my_list))

[1, 1, 2.8, 3, 'english', 'true', 1111, 1]
8


In [ ]:
#deleting elements in a list
my_list =[1,1,2.8,3,"english","true",1111,1]
del my_list[4]
print(my_list)

[1, 1, 2.8, 3, 'true', 1111, 1]


In [ ]:
#adding two list
my_list  =[1,1,2.8,3,"english","true",1111,1]
my_list2 =[1,1,2.8,3,"english","true",1111,1]
my_list3=my_list+my_list2
print(my_list3)


[1, 1, 2.8, 3, 'english', 'true', 1111, 1, 1, 1, 2.8, 3, 'english', 'true', 1111, 1]


#Tuple


In [ ]:
#tuple also alows multiple datatypes
tuple1=(1,2,"machine",5.9)
print(tuple1)
type(tuple1)

(1, 2, 'machine', 5.9)


tuple

In [ ]:
#converting list in to tuple
my_list=[1,2,3,4,5]
print(my_list)
mytuple=tuple(my_list)
print(mytuple)

[1, 2, 3, 4, 5]
(1, 2, 3, 4, 5)


#Set

In [ ]:
#set are curlybracket
#set has not index value
machine={1,2,3,4,5}
type(machine)

set

In [ ]:
#convert list t0 set
List_5=[1,2,3,4,5]
x=set(List_5)
print(x)

{1, 2, 3, 4, 5}


In [ ]:
#set doesn't allow duplicate values
set_3={1,2,3,4,5,6,1,1,5}
print(set_3)

{1, 2, 3, 4, 5, 6}


#Dictionary

In [ ]:
my_dictionary={'name':'sefin','age':30,'country':'India'}
print(my_dictionary)

{'name': 'sefin', 'age': 30, 'country': 'India'}


In [ ]:
print(my_dictionary['name'])
print(my_dictionary['age'])
print(my_dictionary['country'])

sefin
30
India


#If else statement

In [ ]:
#if else
a=int(input("enter the 1 number"))
b=int(input("enter the 2 number"))
if(a>b):
  print("a is greater than b")
else:
  print("b is greater than a")

enter the 1 number5
enter the 2 number1
a is greater than b


In [ ]:

#if elif and else
a=int(input("enter the 1 number"))
b=int(input("enter the 2 number"))
c=int(input("enter the 3 number"))
if(a>b):
  print("a is greater than b")
elif(b>c):

  print("b is greater than c")
else:
  print("c wasted ")

enter the 1 number5
enter the 2 number3
enter the 3 number6
a is greater than b


#Loops

In [ ]:
for i in range(5):
  laptop_price=int(input("enter the price of laptop"))

enter the price of laptop56
enter the price of laptop32
enter the price of laptop456
enter the price of laptop3256
enter the price of laptop451651


In [ ]:
numbers=[1,2,3,4,5,6,7,8,9,9]
for i in numbers:
  print(i)

1
2
3
4
5
6
7
8
9
9


In [ ]:
#while loops
#1st condition check then only it will work,its like if else
i=0
while i<=10:
  print (i)
  i+=1

0
1
2
3
4
5
6
7
8
9
10


#**Functions&&&&&&&&&&&&&**


#Factorial of **number**

In [ ]:
number=int(input("enter your factorial number"))
factorial=1
if number==0:
  print("factorial of 0 is 1")
else:
  for i in range(1, number+1):
    factorial=factorial*i
  print("the factorial of a ",number,"is",factorial)


enter your factorial number5
the factorial of a  5 is 120


In [ ]:
#using function faction
def factorial_value(num):
  factorial=1
  if num==0:
    return factorial
  else:
    for i in range(1, number+1):
      factorial=factorial*i
    return factorial

In [ ]:
print(factorial_value(5))

120


# ** Numpy-Numerical python**
Advantages of Numpy Arrays:
# 1.Allows several mathematical operation
# 2.Faster operations

In [ ]:
import numpy as np


List vs Numpy -Time Taken

In [ ]:
from time import process_time


In [ ]:
python_list=[i for i in range(10000)]
start_time=process_time()
python_list=[i+5 for i in python_list]
end_Time=process_time()
print(end_Time - start_time)

0.0014801089999991746


In [ ]:
np_array=np.array([i for i in range(10000)])
start_time=process_time()
np_array+=5
end_Time=process_time()
print(end_Time - start_time)

0.0016304569999903151


In [ ]:
#list
list1=[1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [ ]:
np_array=np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
import numpy as np


In [ ]:
#creating 1 dim array
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a.shape

(4,)

In [ ]:
b=np.array([(1,2,3,4,5),(23,44,33,22,23)])
print(b)

[[ 1  2  3  4  5]
 [23 44 33 22 23]]


In [ ]:
b.shape

(2, 5)

In [ ]:
c=np.array([(1,2,3,4,5),(23,44,33,22,23)],dtype=float)
print(c)

[[ 1.  2.  3.  4.  5.]
 [23. 44. 33. 22. 23.]]


In [ ]:
#initial place holders in zeros in arrays
x=np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
y=np.ones((4,5))
print(y)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
z=np.full((4,5),9)
print(z)

[[9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]]


In [ ]:
#idemtity ,atrices
k=np.eye(9)
print(k)

[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [ ]:
#create an numpy array with randm values
k=np.random.random((9,8))
print(k)

[[0.06193529 0.39713544 0.25197459 0.85905246 0.27085892 0.77337009
  0.13614615 0.90958462]
 [0.79023207 0.98454128 0.12928474 0.04625733 0.13417178 0.38988301
  0.51029378 0.98748607]
 [0.73534103 0.4709041  0.54497562 0.42939554 0.44558968 0.65427266
  0.73574871 0.65190351]
 [0.25692678 0.28758323 0.16500386 0.27839318 0.13081497 0.37018683
  0.9663183  0.40864963]
 [0.82801046 0.11134425 0.87544908 0.24322126 0.75042436 0.98432733
  0.28969189 0.36811441]
 [0.52093435 0.70033171 0.62676515 0.38462543 0.30999064 0.68206456
  0.61581415 0.99669414]
 [0.4551308  0.0448027  0.16134057 0.25515839 0.08397476 0.49579606
  0.74551808 0.78777571]
 [0.93591676 0.63059413 0.4595492  0.20355799 0.36252561 0.11985713
  0.42053243 0.94560113]
 [0.54853888 0.29740241 0.94358423 0.43896601 0.60857835 0.75139563
  0.26386752 0.65319962]]


In [ ]:
#random array with specific range
s=np.random.randint(1,99,(3,5))
print(s)

[[75 88 56 46 18]
 [26 75 92 54 53]
 [13 78 73 55 63]]


In [ ]:
#array of evenly spaced value-->specifying values are required
d=np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [ ]:
#array of evenly spaced value-->specifying the step
d=np.arange(10,30,5)
print(d)

[10 15 20 25]


In [ ]:
#converting list to numpy array
List2=[1,2,3,4,5]
np_array=np.asarray(List2)
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

#Matrics


In [ ]:
import numpy as np


In [ ]:
a = np.random.randint(7,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [ ]:
print(a)
print(b)

[[9 8 8]
 [7 8 8]
 [7 8 9]]
[[10 14 18]
 [17 11 19]
 [18 13 17]]


In [ ]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[19 22 26]
 [24 19 27]
 [25 21 26]]
[[ -1  -6 -10]
 [-10  -3 -11]
 [-11  -5  -8]]
[[ 90 112 144]
 [119  88 152]
 [126 104 153]]
[[0.9        0.57142857 0.44444444]
 [0.41176471 0.72727273 0.42105263]
 [0.38888889 0.61538462 0.52941176]]


In [ ]:
#this way also add
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[19 22 26]
 [24 19 27]
 [25 21 26]]
[[ -1  -6 -10]
 [-10  -3 -11]
 [-11  -5  -8]]
[[ 90 112 144]
 [119  88 152]
 [126 104 153]]
[[0.9        0.57142857 0.44444444]
 [0.41176471 0.72727273 0.42105263]
 [0.38888889 0.61538462 0.52941176]]


**Array Manipulation**

In [ ]:
array=np.random.randint(0,7,(2,3))
print(array)
print(array.shape)

[[3 4 6]
 [2 5 0]]
(2, 3)


In [ ]:
trans=np.transpose(array)
print(trans)
trans=(trans.shape)

[[3 2]
 [4 5]
 [6 0]]


In [ ]:
#reshaping an array
array=np.random.randint(0,7,(2,3))
print(array)
print(array.shape)


[[1 0 5]
 [6 5 4]]
(2, 3)


In [ ]:
b=array.reshape(3,2)
print(b)

[[1 0]
 [5 6]
 [5 4]]
